#!/bin/bash

run_sql () {
    username=root
    if [[ $2 != "" ]]; then
        username=$2
    fi
    MYSQL_PWD=victory mysql -h127.0.0.1 -P3308 -u$username <$1
}

run_sql /home/createuser.sql
run_sql /home/db.sql admin
